### ISSUE TITLE
variable parsing

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#23]
# What?
- detect variables
- valid input `(VARNAME=CONTENT)` -> doesnt matter how many = signs there are as long as there is one all the following count towards the COTENT
- if variable is already in the variable list then just replace the value
- strdup the value into the struct
- free all the split or whatever

# Structs
```c
typedef struct s_variable
{
	char				*name;
	char				*value;
	struct s_variable	*next;
	struct s_variable	*prev;
}			t_variable;

typedef struct s_shell
{
	bool		run;
	char		*path;
	char		**env;
	char		**envp;
	t_variable	*variables;
}			t_shell;

typedef struct s_command
{
	char				*command;
	char				**args;
	int					*operator_type;
	int					priority;
	struct s_command	*next;
	struct s_command	*prev;
	t_shell				*shell;
}			t_command;
```

!!!EVERYTHING THAT IS MALLOCED IS REFERENCED IN A STRUCT!!!

**Comment by Reptudn** [comment]
git fetch origin
git checkout 23-variable-parsing

**Comment by NoelSabia** [comment]
Just for clarification:
I programmed it so that i assume the input is right! If that is not included we/I need to change that!

**Comment by Reptudn** [comment]
> Just for clarification: I programmed it so that i assume the input is right! If that is not included we/I need to change that!

dont forget that to also filter out the operators that are inside a string because they dont count as operators

**Comment by NoelSabia** [comment]
I got an Idea how we can fix following:
minishell ➜ echo "hello there" && pog=123 && lol=222
result[0] = echo
result[1] = "hello
result[2] = there"
result[3] = &&
result[4] = &&
command not found: &&
-----------------------------------------------------------
Solution: I dont filter that out and instead we also search if this string has an '=' in it. If so that means it is a variable and we can skip it. With that we have all the operators still available and we know what to combine and how to do so.

**Comment by NoelSabia** [comment]
Update: Seems to work!
Following changes were made (if you interested in in):
- utils/make_cmds deleted the part where i wrote a space and a null-terminator
- commands/command_handler: added one more else if to catch that exception
